packages:
  - apps/signer
  - apps/examples/jstz-prediction-market/**
  - packages/**

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - '@taquito/taquito'
  - esbuild
  - sharp
  - unrs-resolver

patchedDependencies:
  '@jstz-dev/jstz-client': patches/@jstz-dev__jstz-client.patch
